src/main/webapp/edit-event-form.html, src/main/webapp/index.html, src/main/webapp/script.js, src/main/webapp/style.css
I added a function to open the general event page on click. I made it a separate function because when we load data from the server, it'll be too dense in the getEvents() function. 
I also added comments to the home page, and conformed the home/create hero-image to match William's search page.
=> Open event page on click

src/main/webapp/search.html, src/main/webapp/style.css
I added a 'search tools' div to contain all the search elements, then applied the same css I used to center the home/create page text. I didn't use the same 'hero-text' div because the search elements need to be moved up a tad.
=> Center search tools

src/main/webapp/script.js, src/main/webapp/search.html, src/main/webapp/style.css
Added the location distance section to the search page as well as making a small change to openEvent().
=> Location distance search

src/main/webapp/edit-event-form.html, src/main/webapp/search.html
=> Add event tags to edit form

src/main/webapp/create-event-form.html, src/main/webapp/create-event.html, src/main/webapp/display-event.html, src/main/webapp/edit-event-form.html, src/main/webapp/index.html, src/main/webapp/my-events.html, src/main/webapp/script.js, src/main/webapp/style.css
Expanded the size of the navbar links so that clicking in an area around the text will also take you to the intended page.
Also moved the navigation bar generation to script.js instead of on each html file, so that it is uniform across pages.
=> Fixes to navigation bar

src/main/webapp/create-event-form.html, src/main/webapp/create-event.html, src/main/webapp/display-event.html, src/main/webapp/edit-event-form.html, src/main/webapp/index.html, src/main/webapp/my-events.html, src/main/webapp/search.html, src/main/webapp/style.css, src/main/webapp/survey.html
I added an event section title to the home page, and updated the survey link style. I decided to create columns for the event page title/location for nicer formatting. I also updated the Search page's nav bar to generate with JS.
=> Add home page event section title

src/main/webapp/create-event-form.html, src/main/webapp/create-event.html, src/main/webapp/display-event.html, src/main/webapp/edit-event-form.html, src/main/webapp/index.html, src/main/webapp/my-events.html, src/main/webapp/script.js, src/main/webapp/search.html, src/main/webapp/style-mobile.css, src/main/webapp/survey.html
Finished up mobile versions for the display-event page (fixed the share buttons and footer), the survey page, and the event lists.
Some changes were made to the javascript code for getEvents() in alignment with these.
=> More changes to mobile layout

LICENSE, src/main/webapp/create-event-form.html, src/main/webapp/create-event.html, src/main/webapp/display-event.html, src/main/webapp/edit-event-form.html, src/main/webapp/index.html, src/main/webapp/my-events.html, src/main/webapp/script.js, src/main/webapp/search.html, src/main/webapp/survey.html
Added a function to check which stylesheet to use on load, based on the ratio of the viewport dimensions.
Additionally, added a file with the Apache license.
=> Add license and stylesheet choosing

src/main/webapp/create-event-form.html, src/main/webapp/display-event.html, src/main/webapp/edit-event-form.html, src/main/webapp/index.html, src/main/webapp/my-events.html, src/main/webapp/script.js, src/main/webapp/search.html, src/main/webapp/style-mobile.css, src/main/webapp/style.css, src/main/webapp/survey.html
Added a function that fetches created and saved events from the servlet on loading my-events.html.
Also did some refactoring on script.js -- grouped functions based on which page(s) they apply to.
=> Update my-events and refactor javascript

src/main/java/com/google/sps/Interactions.java, src/main/java/com/google/sps/servlets/UserServlet.java, src/test/java/com/google/sps/UserServletTest.java
Implemented the doPost method in the UserServlet file, which saves or unsaves an event by its id when a user is logged in.
The UserServletTest file has also been refactored, where callGet and callPost have been added as helper methods.
I added an Interactions.java file where I hope to begin building the interaction history system for recommending but I have not done much with this yet.
=> Saving events

.eslintrc
- Add "browser" environment for pre-defined global variables.
- Update "no-unused-vars" rule to allow functions in the global scope.
=> Update eslint configuration.

src/main/java/com/google/sps/Interactions.java, src/main/java/com/google/sps/servlets/SurveyServlet.java, src/main/java/com/google/sps/servlets/UserServlet.java, src/main/java/com/google/sps/servlets/Utils.java, src/test/java/com/google/sps/EventServletTest.java, src/test/java/com/google/sps/InteractionsTest.java, src/test/java/com/google/sps/SurveyServletTest.java, src/test/java/com/google/sps/TestingUtil.java, src/test/java/com/google/sps/UserServletTest.java
Mostly refactoring, where the code handling login setup for tests has been moved to its own class and static methods.
Added a few comparators to the Utils class, and also added some simplistic matrix/vector methods for the Interactions class (subject to change, nothing has been done with them yet)
=> Refactoring

src/main/java/com/google/sps/servlets/LoadEventServlet.java, src/main/webapp/WEB-INF/jsp/display-event.jsp, src/main/webapp/script.js
With this PR, individual events now load their tags from datastore and display them dynamically. Also, the colors of the event display image and attendee count text now update to match the color of the primary/first tag.
=> Generate Tag Based Features for Individual Events

src/main/webapp/script.js
I've gone through the javascript file and fixed all of the lint errors.
=> Fix lint errors in JS file

src/main/java/com/google/sps/servlets/EventServlet.java, src/main/java/com/google/sps/servlets/LoadEventServlet.java, src/main/webapp/WEB-INF/jsp/display-event.jsp, src/main/webapp/script.js, src/main/webapp/style-mobile.css, src/main/webapp/style.css, src/test/java/com/google/sps/EventServletTest.java, src/test/java/com/google/sps/LoadEventServletTest.java, src/test/java/com/google/sps/UserServletTest.java
Now before the data is loaded into datastore, the date, time and location are formatted according to the original mock UI. Also, there is now a default rainbow gradient image for LGBTQ+ tagged events.
=> Complete Formatting of Individual Event Page

src/main/java/com/google/sps/Utils.java, src/main/java/com/google/sps/servlets/SearchServlet.java, src/main/java/com/google/sps/servlets/UserServlet.java, src/test/java/com/google/sps/EventServletTest.java, src/test/java/com/google/sps/SearchServletTest.java, src/test/java/com/google/sps/SearchTagsServletTest.java, src/test/java/com/google/sps/UserServletTest.java
Moved Utils class to more appropriate place and added the call for the API key method.
=> Secret call

src/main/java/com/google/sps/servlets/EventServlet.java, src/main/java/com/google/sps/servlets/UserServlet.java, src/test/java/com/google/sps/EventServletTest.java, src/test/java/com/google/sps/UserServletTest.java
Added functionality to keep track of attendee count when events are saved/unsaved
=> Keep track of attendee count

src/main/java/com/google/sps/servlets/LoadEventServlet.java, src/main/java/com/google/sps/servlets/SearchServlet.java, src/test/java/com/google/sps/SearchTagsServletTest.java
Fix tags not showing up on event display and multiple tag search queries not returning results.
=> Minor fixes

src/main/java/com/google/sps/servlets/EventServlet.java, src/main/webapp/WEB-INF/jsp/display-event.jsp, src/main/webapp/script.js, src/main/webapp/style-mobile.css, src/main/webapp/style.css
Just a few small mobile fixes to make the locations setting more readable. I also added a function to load optional fields - I plan to use this to load user uploaded images.
=> Small style fixes

src/main/java/com/google/sps/servlets/AuthServlet.java, src/main/java/com/google/sps/servlets/LoadEventServlet.java, src/main/java/com/google/sps/servlets/UserServlet.java, src/main/webapp/WEB-INF/jsp/display-event.jsp, src/main/webapp/index.html, src/main/webapp/script.js
Modifications to front-end of user servlet actions -- checks if an event has already been saved by a user, in order to update the individual display page appropriately. Also uses the checkLogin() to modify how the nav bar is generated, where the upper-right hand corner will either contain a login link or a link to the my events page.
=> User servlet frontend

pom.xml, src/main/java/com/google/sps/Recommend.java, src/test/data/events.csv, src/test/data/userdata.csv, src/test/data/userdatav2.csv, src/test/java/com/google/sps/RecommendTest.java
Used the Apache Spark library to create a simple collaborative filtering recommendation system.
About the .csv files:
userdata.csv and userdatav2.csv -- Records "ratings" by users for each event. userdata.csv uses the linear 0/2/4/6 scoring scale, while userdatav2.csv uses a 0/4/8/10 scoring scale.
events.csv -- some sample events. Used to map to the events ids used in the rating files in order to print out the details if necessary.
Because the Spark library is a bit of a black box when it comes to implementation details and expected output, RecommendTest currently doesn't test anything for "correctness" in same way as the other unit tests, just makes sure that everything performs without errors and that the model's output is in an expected format. I recommend commenting out the test …
=> Recommendations

pom.xml
Added some dependencies that hopefully fix the error that prevents us from running dev servers
=> Fix packaging error

src/main/java/com/google/sps/servlets/LocationServlet.java, src/main/webapp/script.js, src/test/java/com/google/sps/LocationServletTest.java
Added functionality to store a user's location using the Datastore with a fallback on cookies (that also then works if the user is not logged in).
=> User location

src/main/java/com/google/sps/Utils.java, src/main/java/com/google/sps/servlets/KeywordSearchServlet.java, src/main/java/com/google/sps/servlets/SearchServlet.java, src/test/java/com/google/sps/KeywordSearchServletTest.java, src/test/java/com/google/sps/SearchServletTest.java, src/test/java/com/google/sps/SearchTagsServletTest.java
Added a separate search servlet that implements a keyword search/sorting algorithm. Also fixed some random bugs having to do with search.
Still needs to be done:
- Frontend
- Generation of keywords in event creation/editing
=> Keyword search

.github/workflows/codecov.yaml, src/main/java/com/google/sps/Interactions.java
I fixed the warning on the codecov yaml. It still doesn't make comments consistently though.
=> Fix codecov yml warning

src/test/java/com/google/sps/InteractionsTest.java, src/test/java/com/google/sps/UserServletTest.java
Added some tests to cover unchecked edge cases/error handling in UserServlet and Interactions.
=> Additional tests

Dockerfile, src/main/java/com/google/sps/Firebase.java, src/test/java/com/google/sps/FirebaseTest.java, src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Added two tests for the Firebase class to increase test coverage.
=> Firebase tests

Dockerfile, src/main/webapp/script.js
Fixed error that wouldn't allow users to search without specifying a location first.
=> Default location

src/main/java/com/google/sps/servlets/LoadEventServlet.java, src/test/java/com/google/sps/LoadEventServletTest.java
Included more tests for the load event servlet to reach 100% coverage.
=> Increase coverage for load event test

src/main/java/com/google/sps/servlets/EditEventServlet.java, src/main/java/com/google/sps/servlets/EventServlet.java, src/test/java/com/google/sps/FormattingTest.java
Add a few more tests for formatting date/time to increase coverage.
=> Additional format tests

src/main/webapp/WEB-INF/jsp/edit-event-form.jsp, src/main/webapp/create-event-form.html, src/main/webapp/create-event.html, src/main/webapp/script.js, src/main/webapp/style-mobile.css, src/main/webapp/style.css
Made a few small fixes throughout the web app
- File input on the create page is now a hidden field
- Default event background before the page is fully loaded is now white/grey instead of green
- Event tags are now in rows on mobile version instead of columns
- Increased clickable area of edit/unsave event link
- Added verification so only logged in users can access create event page
- Verify tags on form submit to catch unfilled required fields & prepopulate userToken on page load to prevent null pointer exception
=> Small event fixes

src/main/java/com/google/sps/servlets/EditEventServlet.java
Added keyword generation to event editing.
=> Event editing keyword generation

src/main/webapp/script.js, src/main/webapp/search.html, src/main/webapp/style-mobile.css, src/main/webapp/style.css, src/main/webapp/survey.html
- Added loading messages to places that call getEvents()
- Changed JS alerts to modals
- Added a check to make sure the zip code entered is a string containing only numbers
- Removed gap on Firebase login page
=> Quality of life fixes

src/main/java/com/google/sps/servlets/SearchServlet.java
Fixed a bug that caused the sort to not behave how I expected and very infrequently makes searches less relevant.
=> Fixed sort bug

src/main/java/com/google/sps/servlets/SearchServlet.java, src/test/java/com/google/sps/CombineSearchTest.java, src/test/java/com/google/sps/KeywordSearchTest.java, src/test/java/com/google/sps/TagSearchTest.java
Reverts googleinterns/step128-2020#84
=> Revert "Location radius for search"

src/main/webapp/script.js
Fixed bug where all tags would get unselected if you unselected the first tag you selected.
=> Fixed tag bug

src/main/webapp/script.js
Fixed user not being able to click on edit event button.
=> Fix edit event button bug

src/main/java/com/google/sps/servlets/UserServlet.java, src/main/webapp/WEB-INF/index.yaml, src/test/java/com/google/sps/UserServletTest.java
Fixed the DatastoreNeedIndexException by adding an index.yaml file to the project.
=> Fix DatastoreNeedIndexException

pom.xml, src/main/java/com/google/sps/Recommend.java, src/main/java/com/google/sps/servlets/TaskHandler.java, src/test/java/com/google/sps/RecommendTest.java
Changed the method call in the task handler to skip the spark step when it computes the recommendations.
=> Skip spark

src/main/java/com/google/sps/servlets/EditEventServlet.java, src/main/webapp/style-mobile.css
No longer sets attendee count to 0 after editing event. Also, small fixes to edit button and hero text.
=> Attendee count fix
